### ISSUE TITLE
node.js crash

### ISSUE THREAD

**Issue by joosti** [spuleri/Multiple-Choice-App#41]
After submitting the timer on the 'student' froze (no longer counting down), and node.js threw an error (see below). Not sure if this is enough to go on: I had an admin session open, and a student session. Also, I my laptop had gone to sleep mode in the meanwhile (so I continued an old or possibly expired session)

GET /modules/core/img/brand/favicon.ico 304 184.832 ms - -
GET /courses/552fc1c501556db475e130e7 304 390.936 ms - -
GET /%7B%7BcurrentQuestion.imageSource%7D%7D - - ms - -
GET /users 200 186.765 ms - 514
PUT /users 200 252.973 ms - 639
Error: failed to connect to [ds043329.mongolab.com:43329]
    at null.<anonymous> (/home/joost/projects/Multiple-Choice-App/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:555:74)
    at EventEmitter.emit (events.js:106:17)
    at null.<anonymous> (/home/joost/projects/Multiple-Choice-App/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous> (/home/joost/projects/Multiple-Choice-App/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:415:13)

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: failed to connect to [ds043329.mongolab.com:43329]
    at null.<anonymous> (/home/joost/projects/Multiple-Choice-App/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:555:74)
    at EventEmitter.emit (events.js:106:17)
    at null.<anonymous> (/home/joost/projects/Multiple-Choice-App/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous> (/home/joost/projects/Multiple-Choice-App/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:415:13)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by goozie001** [comment]
Hey Joost

Interesting, thank you for logging this bug. I'll ask you to reproduce it
if possible tomorrow when we meet; otherwise, the call stack is helpful
enough as is.

Best regards,
Dylan
